services/csharp/Common.Test/AnalyticsShould.cs
services/csharp/Common.Test/Common.Test.csproj
services/csharp/Common/Analytics/AnalyticsCommandLineArgs.cs
services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/IAnalyticsSender.cs
services/csharp/Common/Analytics/NullAnalyticsSender.cs
services/csharp/Common/Common.csproj
services/csharp/metagame-services.sln

This PR adds the foundations for instrumenting this repo for the reporting of analytics data.
The current state contains some basic classes for achieving this, with the main deficiencies being:
- Currently lacks a method of injecting the GCP key.
- Event categories are always empty.
- Messages are not batched, but instead all sent individually.
I intend to fix these in the next PR to avoid bloating this one too much.

Base for analytics instrumentation system

---

services/csharp/Common.Test/AnalyticsShould.cs
services/csharp/Common.Test/Common.Test.csproj
services/csharp/Common/Analytics/AnalyicsSenderBuilder.cs
services/csharp/Common/Analytics/AnalyticsCommandLineArgs.cs
services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/Config/AnalyticsConfig.cs
services/csharp/Common/Common.csproj

This PR adds analytics configuration file loading which allows event categories to be defined through a YAML file, as well as offering the ability to selectively disable events. There are other things we may want to add in future (such as reporting frequency, batch queue size, etc.) but these should be trivial to add at a later point.
Config files look like such:
```yaml
"party":
"join":
category: "function"
"user":
"leave_party":
category: "cold"
"enter_party":
disabled: true
```
I have some rough documentation for how this file operates, but I'm still working on how everything should fit together so I'd prefer to include that with the first PR that actually adds any instrumentation since it will have been finalised by then.
I've also made some improvements to the testing file since to …

Analytics config

---

services/csharp/Common.Test/AnalyticsShould.cs
services/csharp/Common/Analytics/AnalyicsSenderBuilder.cs
services/csharp/Common/Analytics/AnalyticsCommandLineArgs.cs
services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/Config/AnalyticsConfig.cs
services/csharp/Common/Analytics/IAnalyticsSender.cs
services/csharp/Common/Analytics/NullAnalyticsSender.cs

This PR adds batching to the AnalyticsSender so that messages are not immediately sent but instead batched up and sent periodically or when the batch size becomes too large.
One evil of this PR is a Task.Delay in one of the tests, but I believe it's justified as it's only 20ms (the Common.Test suite as a whole takes ~700-900ms), I *think* NUnit handles async well, and it saves any extra complexity of making a wrapper around the Task library that can be injected. I'm happy to change this to another solution if preferred, though.

Add batching features to the AnalyticsSender

---

services/csharp/Common.Test/AnalyticsShould.cs
services/csharp/Common/Analytics/AnalyicsSenderBuilder.cs
services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/DispatchExceptionLogger.cs
services/csharp/Common/Analytics/ExceptionHandlers/IDispatchExceptionStrategy.cs
services/csharp/Common/Analytics/ExceptionHandlers/LogExceptionStrategy.cs
services/csharp/Common/Analytics/ExceptionHandlers/RethrowExceptionStrategy.cs

This PR tackles the issue that, ideally, sending analytics should be low-effort. Users shouldn't have to wrap every analytics.Send(...) call with a near-identical try-catch blocks to avoid their application crashing, since it disincentives analytics sending.
Added:
* System of `DispatchExceptionStrateg[ies]` which are pretty much a layer over a simple handler (we could also use an action and allow an arbitrary lambda - open to feedback here, though it seems sensible to me to at least provide some pre-defined options)
* A log handler, which I intend to use to instrument the existing services.
* A simple handler for just re-throwing the exception so the user deals with it - essentially a wrapper around the old behaviour. This is enabled by default.
* Corresponding unit tests to verify that …

Add exception handling strategies to analytics sender

---

services/k8s/deployment-pool/deployment.yaml

**Description**
Currently when the deployment pool performs its cleanup as it's being stopped (see code [here](https://github.com/spatialos/online-services/blob/235aacf3b39a2eb95fc54569ec18fa05b4a9c3ce/services/csharp/DeploymentPool/DeploymentPool.cs#L52)) it might take more than 30  seconds to stop all the deployments. As a result not all of the deployments have been stopped (~ 80 deployments are usually stopped within the period). This increases the termination grace period to 300 seconds.

Deployment pool extend grace period

---

services/csharp/Common.Test/AnalyticsShould.cs
services/csharp/Common/Analytics/AnalyicsSenderBuilder.cs
services/csharp/Common/Analytics/AnalyticsCommandLineArgs.cs
services/csharp/Common/Analytics/AnalyticsEnvironment.cs
services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/AnalyticsSenderClassWrapper.cs
services/csharp/Common/Analytics/IAnalyticsSender.cs
services/csharp/Common/Analytics/IAnalyticsSenderExtensions.cs
services/csharp/Common/Analytics/NullAnalyticsSender.cs

This PR makes a variety of changes which made instrumenting Party (next PR) more straightforward. My focus was on minimising duplication where possible to make the user-level instrumentation as minimal as possible.
Main changes:
* Accept generic type T to Send to allow non-string data e.g. lists to be encoded into JSON correctly. For most events, T = string.
* Delete `development` environment
* Add GcpKeyPath and environment command line flags
* Split `Send` into `Send` and `SendAsync`.
* Add a `AnalyticsSenderClassWrapper` which wraps around `IAnalyticsSender` and provides some utility methods to avoid having to pass in `eventClass` every time, since it's typically the same.
* This could easily be part of the ordinary interface with a specific default provided, but tricky behaviour if …

Various changes to analytics in advance of instrumenting Party/

---

services/csharp/Party.Test/CreateInviteShould.cs
services/csharp/Party.Test/CreatePartyShould.cs
services/csharp/Party.Test/DeleteInviteShould.cs
services/csharp/Party.Test/DeletePartyShould.cs
services/csharp/Party.Test/GetInviteShould.cs
services/csharp/Party.Test/GetPartyByPlayerIdShould.cs
services/csharp/Party.Test/JoinPartyShould.cs
services/csharp/Party.Test/KickOutPlayerShould.cs
services/csharp/Party.Test/LeavePartyShould.cs
services/csharp/Party.Test/ListAllInvitesShould.cs
services/csharp/Party.Test/UpdateInviteShould.cs
services/csharp/Party.Test/UpdatePartyShould.cs
services/csharp/Party/InviteServiceImpl.cs
services/csharp/Party/PartyServerCommandLineArgs.cs
services/csharp/Party/PartyServiceImpl.cs
services/csharp/Party/Program.cs

Nothing new in this PR from what was previously in the other PR except for how the command line arg class is set up.
There is a little redundancy in PartyServiceCommandLineArgs now, but some nice benefits:
* Don't need to parse twice
* Can still forbid unknown arguments

Instrument party and invite services

---

services/csharp/Common/Analytics/AnalyticsSender.cs
services/csharp/Common/Analytics/AnalyticsSenderClassWrapper.cs
services/csharp/Common/Analytics/IAnalyticsSender.cs
services/csharp/Common/Analytics/NullAnalyticsSender.cs

This PR introduces three things:
- It pulls `playerId` out of eventAttributes, and turns it into an optional argument to pass in while using the `.Send()` method. If it is passed, it is now a root key of the event JSON object, instead of being inside `eventAttributes`. If it is not passed, it is simply not present in the JSON object. This change was requested by NWX.
- The analytics configuration was not working properly, disabling events did not actually prevent them from being sent. This is now fixed.
- `eventTimestamp` is upgraded from ToUnixTimeSeconds to ToUnixTimeMilliseconds, which is actually very helpful when there are loads of events being generated & you are sorting them by `eventTimestamp`.

fix analytics sender

---

services/csharp/DataModel.Test/EntryDeserializeShould.cs
services/csharp/DataModel/DataModel.csproj
services/csharp/DataModel/Entry.cs
services/csharp/DataModel/Gateway/PartyJoinRequest.cs
services/csharp/DataModel/Gateway/PlayerJoinRequest.cs
services/csharp/Gateway.Test/OperationsServiceDeleteOperationShould.cs
services/csharp/Gateway.Test/OperationsServiceGetOperationShould.cs
services/csharp/Gateway/GatewayServiceImpl.cs
services/csharp/Gateway/OperationsServiceImpl.cs
services/csharp/Gateway/Program.cs
services/csharp/Proto/generated/Gateway.cs
services/proto/gateway/gateway.proto

This PR instruments the Gateway, and includes some changes to the data model so that `partyJoinRequests` contain a `matchRequestId`, and a playerJoinRequest contains a `partyId` and a `matchRequestId` - which facilitates better tracking.
Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=0 (where `eventSource` = `gateway_gateway`).

instrumented Gateway

---

docs/content/get-started/quickstart-4.md
services/k8s/playfab-auth/deployment.yaml

Update the documentation and deployment config to read the PlayFab secret from a literal rather than a file. Avoids BOM and newline issues.

Read PlayFab secret from literal value rather than a file

---

services/k8s/config.yaml
services/k8s/sample-matcher/deployment.yaml

Did a QA pass today re-rolling out all services. I wanted to try using a different queue type than `match` and see whether the system still worked using the SampleClient.
I updated:
- The deployment pool setup [here](https://github.com/spatialos/online-services/blob/master/services/k8s/deployment-pool/deployment.yaml#L56
).
- The SampleClient [here](https://github.com/spatialos/online-services/blob/master/services/csharp/SampleClient/Program.cs#L104).
This wasn't enough, because I forgot the Matcher is defaulting to `match` unless you pass it a `MATCH_TAG` environment variable through its k8s configuration file. This wasn't obvious because our template isn't doing this, and is instead currently relying on [this default](https://github.com/spatialos/online-services/blob/master/services/csha …

explicitly set the default match tag used by matcher

---

services/terraform/services.tf

Encountered a small issue when deploying the Online Services including analytics in a fresh project, forgot to enable the Cloud Function API with Terraform.

added enablement of cloud function api to terraform

---

services/csharp/Base.Server/Base.Server.csproj
services/csharp/Common/Common.csproj
services/csharp/Common/Common.nuspec
services/csharp/Proto/Proto.csproj
services/csharp/Proto/generated/GatewayGrpc.cs
services/csharp/Proto/generated/GatewayInternal.cs
services/csharp/Proto/generated/GatewayInternalGrpc.cs
services/csharp/Proto/generated/Invite.cs
services/csharp/Proto/generated/InviteGrpc.cs
services/csharp/Proto/generated/Party.cs
services/csharp/Proto/generated/PartyGrpc.cs
services/csharp/Proto/generated/PlayfabGrpc.cs

Upgrade `Grpc.Core` and `Grpc.Tools` across solution to 2.24.0. This is equivalent to gRPC version 1.24.0; the [major version bump](https://github.com/grpc/proposal/blob/master/L57-csharp-new-major-version.md) was caused by a breaking changed needed to support .NET Core 3.0.

Upgrade gRPC packages across solution to 1.22.1

---

.buildkite/premerge.steps.yaml

Update to use the combined 2.2 and 3.0 .NET builder.
Also ensure the unit and integration tests only run after the initial build phase completes, to mitigate Nuget clashes.

Update builder queue

---

tools/ServiceAccountCLI/Program.cs
tools/ServiceAccountCLI/README.md

Adds read permission for `srv/pkg` by default to created service accounts.
This permission allows for retrieving packages (e.g. worker SDKs, schema etc.), typically used for building SpatialOS projects.
It is set by default as opposed to exposing it as a flag because:
* The permission isn't sensitive
* This is consistent with how we handle read permissions for `srv/bundle` which allows downloading versions of the runtime (required for running SpatialOS projects).
Service accounts generated by this tool are not only being used for running online services but also for building and running SpatialOS projects in CI.
Verified by generating a token and using it to retrieve packages via `spatial package get`.
* Fix a link in the docs
* Print a message suggesting to users to try running `spatial …

Give service accounts package read permissions by default.

---

services/csharp/Gateway/GatewayServiceImpl.cs

I've just lifted this wholesale from the old `OperationsService`. The `GetOperation` RPC was not instrumented so I haven't touched the `GetJoinStatus`.

Instrument CancelJoin RPC

---

services/terraform/module-analytics/service-accounts-endpoint.tf
services/terraform/module-analytics/service-accounts-function.tf

This PR tightens the GCS permissions for two analytics service-accounts:
* The service account used by the Endpoint can now only _write_ into GCS.
* The service account used by the Cloud Function can now only _read_ from GCS.
Instead of going down the path creating [custom roles](https://cloud.google.com/iam/docs/creating-custom-roles), I decided to stick with the [readily available roles](https://cloud.google.com/storage/docs/access-control/iam-roles) for simplicity, although this does mean I had to add two roles. In particular `roles/storage.legacyBucketReader` was necessary to provide the `storage.buckets.get` permission.
Integration test succeeded:
```sql
SELECT * FROM `logical-flame-194710.events.events_function_native`
WHERE event_class = 'permission-test';
```

restricted SA GCS access to read/write

---

services/python/analytics-pipeline/src/dataflow/common/functions.py
services/python/analytics-pipeline/src/function/main.py
services/terraform/module-analytics/cloud-function.tf

This PR optimizes the analytics Cloud Function's memory usage so it can use [the smallest / cheapest template](https://cloud.google.com/functions/pricing) (128 MB / 200 MHz).
The biggest file size our Cloud Endpoint currently accepts is 32MB - I have tested and verified files of this size still succeed. Another large scale test with many files of much smaller size also succeeded.
I've changed two additional minor things:
* Switched to use the latest Python 3 string formatting structure.
* It no longer silently INFO logs BigQuery insertion errors, but raises an Exception.

optimized cloud function to be able to use smallest template

---

.buildkite/premerge.steps.yaml
ci/analytics-endpoint.sh
docs/content/services-packages/analytics-pipeline/local.md
services/docker/docker_compose_local_analytics_pipeline.yml

The new BuildKite images run a Goss status check on port 8080, so this also tweaks the local docker-compose configuration to expose the analytics service on host port 9090.

Upgrade BuildKite queue, fix analytics CI

---

.buildkite/premerge.steps.yaml

Added some missing definitions to more tightly target agents. https://docs.improbable.io/internal/platform/product-groups/dev-workflow/buildkite/how-to-autoscale-agents-to-match-demand
* node_stability = interruptible so that there's an 80% reduction in compute spend for the tradeoff of an agent node being shut down at random within 24 hours of being started. Since your jobs all seem to be sub five minutes, that seems like a very worthwhile tradeoff.
* make environment overridable via a var
* specify a machine_type to be explicit (same naming as spatialOS node sizes)
* specify a platform to be explicit (we're planning on soon making it possible for a single queue to contain more than one image)
Add another BK-system-error code for auto-retry.

Update CI agent targeting rules
