- docs/content/integrations/database-sync-worker.md
No content changes. Just fix a lint issue.
> Resolve a lint issue

- docs/index.md
Making some very minor updates as it's the first time I've edited these docs.
> Remove a few full stops

- services/csharp/Party.Test/AnalyticsConstants.cs
- services/csharp/Party.Test/CreateInviteShould.cs
- services/csharp/Party.Test/CreatePartyShould.cs
- services/csharp/Party.Test/DeleteInviteShould.cs
- services/csharp/Party.Test/DeletePartyShould.cs
- services/csharp/Party.Test/JoinPartyShould.cs
- services/csharp/Party.Test/KickOutPlayerShould.cs
- services/csharp/Party.Test/LeavePartyShould.cs
- services/csharp/Party.Test/UpdatePartyShould.cs
Had a bit of unallocated time between projects today so threw some unit testing together for the analytics as promised
> Analytics unit tests

- .buildkite/premerge.steps.yaml
> moved to scaler-v2

- docs/content/get-started/quickstart-3.md
- docs/content/get-started/quickstart-4.md
- docs/content/get-started/quickstart-5.md
- docs/content/get-started/quickstart.md
- services/k8s/config.yaml
- services/k8s/deployment-pool/deployment.yaml
- services/k8s/gateway-internal/deployment.yaml
- services/k8s/gateway/deployment.yaml
- services/k8s/gateway/service.yaml
- services/k8s/party/deployment.yaml
- services/k8s/party/service.yaml
- services/k8s/playfab-auth/deployment.yaml
- services/k8s/playfab-auth/service.yaml
- services/k8s/sample-matcher/deployment.yaml
- Made some steps and phrases more explicit so they're easier to follow.
- Added a table of K8s config variable names and example values to aid substitution.
- Replaced square brackets in config files with curly brackets and normalised the variable names to make automated substitution less error-prone.
> Quick start improvements

- services/csharp/Party.Test/CreateInviteShould.cs
- services/csharp/Party.Test/CreatePartyShould.cs
- services/csharp/Party.Test/DeleteInviteShould.cs
- services/csharp/Party.Test/DeletePartyShould.cs
- services/csharp/Party.Test/JoinPartyShould.cs
- services/csharp/Party.Test/KickOutPlayerShould.cs
- services/csharp/Party.Test/LeavePartyShould.cs
- services/csharp/Party.Test/UpdatePartyShould.cs
- services/csharp/Party/InviteServiceImpl.cs
- services/csharp/Party/PartyServiceImpl.cs
- services/csharp/Proto/generated/PartyGrpc.cs
- services/proto/party/party.proto
This PR contains the changed to instrument the Party service.
Full Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=0 (where `eventSource` = `gateway_party`).
> instrumented the party service

- services/csharp/GatewayInternal.Test/AssignDeploymentsShould.cs
- services/csharp/GatewayInternal.Test/ListWaitingPartiesShould.cs
- services/csharp/GatewayInternal/GatewayInternalServiceImpl.cs
- services/csharp/GatewayInternal/Program.cs
- services/csharp/Proto/generated/GatewayInternal.cs
- services/proto/gateway/gateway_internal.proto
This PR contains the changes to instrument the internal gateway.
Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=0 (where `eventSource` = `gateway_internal`).
> instrument internal gateway

- services/csharp/PlayFabAuth/PlayFabAuthImpl.cs
- services/csharp/PlayFabAuth/Program.cs
This PR contains the code to instrument PlayFab Auth.
Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=1374803383
> instrument playfab auth

- services/csharp/SampleClient/Program.cs
- services/csharp/SampleMatcher/Matcher.cs
- services/csharp/SampleMatcher/Program.cs
- services/csharp/SampleMatcher/SampleMatcher.csproj
This PR contains the changes to instrument the sample matcher.
Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=0 (where `eventSource` = `gateway_matcher`).
> instrumented sample matcher

- .buildkite/premerge.steps.yaml
- ci/build.sh
- services/csharp/DataModel.Test/DataModel.Test.csproj
- services/csharp/DeploymentPool.Test/DeploymentPool.Test.csproj
- services/csharp/Gateway.Test/Gateway.Test.csproj
- services/csharp/GatewayInternal.Test/GatewayInternal.Test.csproj
- services/csharp/IntegrationTest.Matcher/IntegrationTest.Matcher.csproj
- services/csharp/IntegrationTest/IntegrationTest.csproj
- services/csharp/IntegrationTest/PartySystemShould.cs
- services/csharp/IntegrationTest/test.ps1
- services/csharp/IntegrationTest/test.sh
- services/csharp/MemoryStore.Test/MemoryStore.Test.csproj
- services/csharp/Party.Test/Party.Test.csproj
Adds report that shows which tests failed on buildkite
> Enable Nunit test reporting in buildkite

- services/csharp/Common/Analytics/AnalyticsSender.cs
- services/csharp/DeploymentPool/DeploymentPool.cs
- services/csharp/DeploymentPool/DeploymentPool.csproj
- services/csharp/DeploymentPool/PlatformInvoker.cs
- services/csharp/DeploymentPool/Program.cs
- services/k8s/deployment-pool/deployment.yaml
This PR instruments the Deployment Pool.
Hook overview: https://docs.google.com/spreadsheets/d/1nlEWy5b97IMdpmHXWLrv5ZtuU3YnU3Ba6-JmVBxB238/edit#gid=1273567465
> instrumented deployment pool

- services/docker/docker_compose_local_analytics.yml
- services/docker/docker_compose_local_services.yml
Another nit - forgot to upgrade the ESP container version in the docker compose files. We already upgraded them in the Kubernetes configuration files.
> upgraded ESP container version in docker compose

- docs/content/configuration-examples/deployment-pool/usage.md
- Fixed sentence in deployment pool setup guide
- Updated deployment square brackets in deployment pool doc to match the new curly braces in config file
> Docs deployment pool fixes

- docs/content/get-started/quickstart-4.md
> PlayFab ID's can be alphanumeric

- .buildkite/premerge.steps.yaml
- ci/build.sh
- ci/integration-tests.sh
- ci/unit-tests.sh
Unit and Integration tests now run in parallel
> split build, unit and integration tests into separate CI steps

- services/csharp/IntegrationTest/GatewayPerformanceShould.cs
Not important, they were just annoying.
> Fix build warnings in integration test

- services/python/analytics-pipeline/src/endpoint/main.py
I've updated most of the analytics endpoint code to follow the latest Python string formatting style, which is significantly more user friendly.
> updated endpoint string formatting style

- services/python/analytics-pipeline/src/endpoint/common/functions.py
- services/python/analytics-pipeline/src/endpoint/main.py
Adding logic so that the Endpoint can handle PlayFab's event webhook forwarding system.
> Endpoint playfab support

- docs/content/services-packages/deployment-pool/deploy.md
> add build step

- .buildkite/premerge.steps.yaml
Another new build queue with an updated Docker role and Windows Server 2019 support.
> Update BuildKite build queue

- README.md
Update readme.md docs links to point to new site.
> Update links to point to new doc site
